/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton/AppButton.vue')['default']
    AppFooter: typeof import('./../src/components/AppFooter/AppFooter.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader/AppHeader.vue')['default']
    AppInput: typeof import('./../src/components/AppInput/AppInput.vue')['default']
    AppSelect: typeof import('./../src/components/AppSelect/AppSelect.vue')['default']
    AppSlider: typeof import('./../src/components/AppSlider/AppSlider.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElLinkt: typeof import('element-plus/es')['ElLinkt']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    IconButton: typeof import('./../src/components/AppHeader/components/IconButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
