/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/common/AppButton/AppButton.vue')['default']
    AppFooter: typeof import('./../src/components/common/AppFooter/AppFooter.vue')['default']
    AppHeader: typeof import('./../src/components/common/AppHeader/AppHeader.vue')['default']
    AppInput: typeof import('./../src/components/common/AppInput/AppInput.vue')['default']
    AppLazyImage: typeof import('./../src/components/common/AppLazyImage.vue')['default']
    AppRouterLink: typeof import('./../src/components/common/AppRouterLink.vue')['default']
    AppSelect: typeof import('./../src/components/common/AppSelect/AppSelect.vue')['default']
    AppSlider: typeof import('./../src/components/common/AppSlider/AppSlider.vue')['default']
    CarCard: typeof import('./../src/components/CarCard/CarCard.vue')['default']
    CarInfoWithIcon: typeof import('./../src/components/CarCard/components/CarInfoWithIcon.vue')['default']
    CarsCarousel: typeof import('./../src/components/CarsCarousel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    FavoriteCarsBrands: typeof import('../src/views/Home/components/FavoriteCarsBrandsSection.vue')['default']
    FavoriteCarsBrandsSection: typeof import('./../src/views/Home/components/FavoriteCarsBrandsSection.vue')['default']
    HeroSection: typeof import('./../src/views/Home/components/HeroSection.vue')['default']
    IconButton: typeof import('./../src/components/common/AppHeader/components/IconButton.vue')['default']
    OffersSection: typeof import('./../src/views/Home/components/OffersSection.vue')['default']
    PopularSearch: typeof import('../src/views/Home/components/PopularSearches.vue')['default']
    PopularSearches: typeof import('./../src/views/Home/components/PopularSearches.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSection: typeof import('./../src/views/Home/components/SearchSection/SearchSection.vue')['default']
    SellingSection: typeof import('./../src/views/Home/components/SellingSection.vue')['default']
  }
}
